//==================================================
//     Outputs that match the input variables
//==================================================
output "name" {
  description = "The value of the `name` input variable."
  value       = var.name
}
output "versioned" {
  description = "The value of the `versioned` input variable."
  value       = var.versioned
}
output "mfa_delete_enabled" {
  description = "The value of the `mfa_delete_enabled` input variable."
  value       = var.mfa_delete_enabled
}
output "object_lock_enabled" {
  description = "The value of the `object_lock_enabled` input variable."
  value       = var.object_lock_enabled
}
output "force_destroy" {
  description = "The value of the `force_destroy` input variable."
  value       = var.force_destroy
}
output "bucket_policy_json_documents" {
  description = "The value of the `bucket_policy_json_documents` input variable."
  value       = var.bucket_policy_json_documents
}
output "kms_key_arn" {
  description = "The value of the `kms_key_arn` input variable."
  value       = var.kms_key_arn
}
output "enable_transfer_acceleration" {
  description = "The value of the `enable_transfer_acceleration` input variable."
  value       = var.enable_transfer_acceleration
}
output "block_public_acls" {
  description = "The value of the `block_public_acls` input variable."
  value       = var.block_public_acls
}
output "block_public_policy" {
  description = "The value of the `block_public_policy` input variable."
  value       = var.block_public_policy
}
output "ignore_public_acls" {
  description = "The value of the `ignore_public_acls` input variable."
  value       = var.ignore_public_acls
}
output "restrict_public_buckets" {
  description = "The value of the `restrict_public_buckets` input variable."
  value       = var.restrict_public_buckets
}
output "object_ownership" {
  description = "The value of the `object_ownership` input variable."
  value       = var.object_ownership
}
output "append_region_suffix" {
  description = "The value of the `append_region_suffix` input variable."
  value       = var.append_region_suffix
}
output "force_allow_cloudtrail_digest" {
  description = "The value of the `force_allow_cloudtrail_digest` input variable."
  value       = var.force_allow_cloudtrail_digest
}

//==================================================
//       Outputs generated by this module
//==================================================
output "region" {
  description = "The name of the region that the bucket was created in."
  value       = data.aws_region.current.name
}

output "bucket" {
  description = "The `aws_s3_bucket` resource that was created."
  value       = aws_s3_bucket.this
}

output "outbound_replication_policy_json" {
  description = "A JSON policy that grants permission to replicate objects out of this bucket."
  value       = data.aws_iam_policy_document.outbound_replication.json
}

output "inbound_replication_policy_json" {
  description = "A JSON policy that grants permission to replicate objects into this bucket."
  value       = data.aws_iam_policy_document.inbound_replication.json
}

output "complete" {
  depends_on = [
    aws_s3_bucket_accelerate_configuration.this
  ]
  description = "Always `true`, but doesn't return until everything in this module has been applied."
  value       = true
}
